### ISSUE TITLE
Get started on Web site http://www.forms-angular.org/#/get-started

### ISSUE THREAD

**Issue by spallesen** [forms-angular/forms-angular#58]
seems to be missing some sections - you refer to details throughout your web site that is not present in the Get Started section?

I especially miss guidance and example code on the AngularJs end - that is getting from the Mongoose schema to what ever needs to get setup in angular to make the conversion to the html.

Thanks and best  regards

**Comment by mchapman** [comment]
Hi, and thanks for the feedback.  I did completely change the getting started section for 0.4 and I can believe I left in some links with text relating to the old content.  Is that the problem you are talking about?
Could you give me an example (URL and text I can search for within the page)?

The easiest way to find what you need is to run
```npm install -g generator-fng
yo fng```
and then have a look in client/app/app.js (the modules depended on and the formsAngular.config bit) and client/partials.

**Comment by spallesen** [comment]
You refer to non-exiting sections in Get Started under Mongoose Schemas in the Schemas section: http://www.forms-angular.org/#/get-started#server-code

Im specially interested in what the best practise process is for exposing a Mongoos model to a view in angular.

**Comment by mchapman** [comment]
Thanks for that, it gives me something to search for (though you could save me the time by telling me where I link to that *from*).

As I said above, the easiest way to get some working code is to generate an app using the yeoman generator.  The code you want will be in server/forms-angular-models (where the Mongoose schemas live) and server/app.js (the code that registers them).

**Comment by spallesen** [comment]
The link appears under Mongoose Schemas in the Schemas section :-)

I have installed the app and begun to reverse engineer the configuration :-)
