### ISSUE TITLE
Single file upload

### ISSUE THREAD

**Issue by bygiro** [forms-angular/forms-angular#59]
Hi, I really like your project!
I have few questions:

1) how can I limit the number of file uploaded?
2) what's the best way to have a single file upload input field instead of a multi upload input field?

**Comment by mchapman** [comment]
Hi

Really glad you like it and thanks for saying so (can't get too many strokes!)

This issue really belongs in the plugin repo, so I have opened it at https://github.com/forms-angular/fng-jq-upload/issues/3 and am closing this.

Mark

**Comment by bygiro** [comment]
ok thanks.....I was also thinking to a MIN / MAX  option for arrays.
I've added the sorting option for arrays, I'll do a PR in the next days, I've firstly to complete some work today.

**Comment by mchapman** [comment]
Cool - another thing I have been meaning to do for quite a while!

I do have a question I would like to ask you but not here - can you email me (it is in the package.json) so we can converse offline?

Mark
