### ISSUE TITLE
Fantastic framework - THX!!! Question: Role based access control

### ISSUE THREAD

**Issue by spallesen** [forms-angular/forms-angular#60]
Thanks for an very impressive and very useful framework. And huge complement for the quality and rubutsness of the implementation - way above many other MEAN implmentations.

Question: Do you have some recommendations/pointers to how you would implement role based access control on the data (i can do done i so many different ways - but wanted to pick your brains before diving into the challange)

All the best !

**Comment by spallesen** [comment]
Just to be a bit more specific ... the first basic scenario is simply to restric users to only see documents from a collection they themsleves have created.

Admin users should see all documents.

**Comment by mchapman** [comment]
Hi

Thanks for the kind words!

I have done a superset of this in the major project I am building from forms-angular (users get access to their own "organisation" and descendant organisations, and view access to parent organisations).  It is closed source at the moment but will eventually be open-source under GPL(v3).  If you want a sneak preview email me using the address in the package.json and I will give you access offline (and if you wanted to extract that functionality up into an elegant plugin that would be great!).

Mark
