### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by spallesen** [forms-angular/forms-angular#62]
Hi, when doing a new standard install with: "yo fng" it installs and works but i get the error meassages below, can you help me out on what it means and if i should care? Kind regards

From the npm-debug.log:

121821 error EEXIST, mkdir 'D:\Dropbox\n2\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download'
File exists: D:\Dropbox\n2\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download
Move it away, and try again.
121822 error System Windows_NT 6.2.9200
121823 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
121824 error cwd D:\Dropbox\n2
121825 error node -v v0.10.30
121826 error npm -v 1.4.21
121827 error path D:\Dropbox\n2\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download
121828 error fstream_path D:\Dropbox\n2\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download\index.js
121829 error fstream_type File
121830 error fstream_class FileWriter
121831 error code EEXIST
121832 error errno 47
121833 error fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
121833 error fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:37:53
121833 error fstream_stack Object.oncomplete (fs.js:107:15)
121834 verbose exit [ 47, true ]

**Comment by mchapman** [comment]
I'm afraid I can't help with the detail of that as I have never used npm on Windows.  But I have a few suggestions:
* Clear out your npm cache
* Upgrade npm ([this](http://stackoverflow.com/questions/26908899/how-do-i-update-npm-on-windows) seems to offer advice about how to do that on Windows)
* It looks like you are using your looking Dropbox drive for your npm files.  If so I would stop doing that.
