### ISSUE TITLE
Label aignment

### ISSUE THREAD

**Issue by audoeyop** [forms-angular/forms-angular#65]
Awesome piece os software.  However, I noticed that whenever I set the model (eg. below), the labels alignment changes from being aligned right to being aligned left.

```
<form-input model="xyz"
```

**Comment by audoeyop** [comment]
Investigating... It looks like when I set the "model" attribute, then the <form class="form-horizontal"> tag doesn't encapsulate my form.  However, if I don't set it, then the <form class="form-horizontal"> tag is rendered in the frm.

**Comment by audoeyop** [comment]
Further investigation, looked at the code and it appears that this is the cause:

forms-angular/dist/forms-angular.js:837
```
if ((attrs.subschema || attrs.model) && !attrs.forceform) {
                elementHtml = '';
              } else {
```
When I added the forceform="true" attribute to the `<form-input>`, the form tag was rendered, which fixes my problem, but I wish there was some documentation for this feature.  I'll go ahead & close this Issue. Thanks for all of the time & effort that you have put into this.

**Comment by mchapman** [comment]
Hi

Thanks for the interest in forms-angular.  Looks like you sorted this out while I was in bed (again, thanks).

This 'feature' is in the docs (in the http://www.forms-angular.org/#/forms#form-input-directive section) which seemed to be the most logical place for it.  Where do think it could be added to save people wasting time in the future?

Mark
