### ISSUE TITLE
Use form object fields without using mongoose

### ISSUE THREAD

**Issue by Karnith** [forms-angular/forms-angular#73]
Is there a way to use the form object fields without using mongoose to create schema?
http://www.forms-angular.org/#/schemas#form-object

I am using an orm and would like the advanced features of the object fields, but do an ng-submit to a back end api I am creating. i've been trying, but have been unsuccessful in my attempts....

**Comment by mchapman** [comment]
Thanks for your interest in forms-angular.

The answer is a qualified "Yes", but there (as you have already discovered) it is a bit tricky.  The mapping from **_Mongoose Schema + Contained Form Objects_** to **_[Form Schemas](http://www.forms-angular.org/#/schemas#formschema) + quite random bits of code_** is complicated, so it depends what features you want to use.

Probably the easiest way to figure out the mapping is to create the Mongoose Schema with embedded Form Objects in a simple app, then output the screen using https://github.com/forms-angular/website/blob/master/app/partials/base-edit.html and uncomment out https://github.com/forms-angular/website/blob/master/app/partials/base-edit.html#L17 - hopefully you will then be able to see what you need to see.  If not feel free to come back with specific queries and I will try to help out.

I do use the formSchema without Mongoose schemas a fair bit in my apps, for login pages, modal dialogues etc., and if it is non trivial I often use this technique to give me a leg-up with the formSchema, which you can sometimes just copy and paste.
