### ISSUE TITLE
blueimp.fileupload error

### ISSUE THREAD

**Issue by jckermagoret** [forms-angular/forms-angular#74]
Hi,
installation is ok and grunt serve seems to be ok. But when browser is launched, the following error appears inthe console :

TypeError: require is undefined
...ride&&(require_baseUrl_override="../"),require.config({baseUrl:require_baseUrl_o...
in jspdf.min.js (ligne 273, col. 21893)

Then another error (maybe related?) :
Error: [$injector:modulerr] Failed to instantiate module tmpApp due to:
[$injector:modulerr] Failed to instantiate module uploadModule due to:
[$injector:modulerr] Failed to instantiate module blueimp.fileupload due to:
[$injector:nomod] Module 'blueimp.fileupload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=blueimp.fileupload
minErr/<@http://localhost:9000/bower_components/angular/angular.js:68:12

...

But blueimp.fileupload is there in client/bower/blueimp-file-upload.

Any ideas ?
Any idea ?

**Comment by mchapman** [comment]
Hi, and thanks for your interest in forms-angular.

Could be a problem with wiredep.  Does it appear in your index.html?

**Comment by jckermagoret** [comment]
Yes,
it appears when accessing index.html.

JC

Le 13/10/2015 17:54, Mark Chapman a écrit :
>
> Hi, and thanks for your interest in forms-angular.
>
> Could be a problem with wiredep. Does it appear in your index.html?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/forms-angular/forms-angular/issues/74#issuecomment-147758158>.
>

-- 
Jean-Christophe KERMAGORET
Directeur associé

BlueXML
40, bd Jean INGRES
44 100 France

http://www.bluexml.com

**Comment by mchapman** [comment]
Am carrying this conversation on in gitter...
