### ISSUE TITLE
TemplatePath or overwriting builtInRoutes

### ISSUE THREAD

**Issue by mjvanderveen** [forms-angular/forms-angular#80]
Hi, I have trouble changing the path of the templates from partial/ to another location. It is because there is no parameter to define the template path. Or alternatively to overwrite the builtInRoutes. It would be helpful if this can be implemented in the core code, so that I can keep updating future edits.

**Comment by mchapman** [comment]
Hi Maarten, and thanks for your interest in forms-angular.  You are absolutely right, and I will look to incorporate your ideas at some point.  If you want it doing in a specific time frame I am happy to help you with a PR.

**Comment by mchapman** [comment]
Am just about to start work on the partials thing, but on re-reading what you have written I thought you may not have realised that you can over-ride any of the views?  There are examples in the forms-angular website around https://github.com/forms-angular/website/blob/master/app/scripts/app.js#L46
