### ISSUE TITLE
show _id field in the generated form

### ISSUE THREAD

**Issue by syedfaizan** [forms-angular/forms-angular#83]
I have a schema similar to this, and i need to set the _id field to be a String field instead of ObjectId.

the problem  is i can't get this field to show in the form (i guess _id field is hidden by default)

is it possible to optionally show _id for some forms? if so please help

```
const mongoose = require('mongoose');
var ObjectId = mongoose.Schema.Types.ObjectId;

const schema = new mongoose.Schema({
  _id: { type:String,form: {hidden:false}},
  createdAt: { type: Date, default: Date.now,form: {hidden:true} },
  updatedAt: { type: Date, default: Date.now,form: {hidden:true} }
});


 module.exports = mongoose.model('tag', schema );
```

**Comment by mchapman** [comment]
You could certainly do this in a somewhat hacky way using a fake field and a directive (there is a simple example of using a directive in the b_enhanced_schema example in the email field).  I cam not sure I can see a reason for making it a general case though.

What is your use case?

**Comment by syedf** [comment]
i wanted to have a different model for tags, and products can add those tags, and instead of saving Object Ids of tags in products, i wanted to save the tag name itself. so when i look at the products db entry i get list of tags, but they also double as the _id field.

**Comment by mchapman** [comment]
Not sure I see why you would need a tags collection in this case?  Would you not be as well off using an **enum** in the product collection?
