### ISSUE TITLE
How to get a datepicker for Date fields?

### ISSUE THREAD

**Issue by syedf** [forms-angular/forms-angular#84]
i have date fields in my form and i need a date picker for Date fields, i have specified in the model that the field is a Date field type, can someone tell me how to get the datepicker working?

**Comment by mchapman** [comment]
Hi

There is an example at https://www.forms-angular.org/#/b_enhanced_schema/new - the Date of Birth field.  It uses the https://github.com/forms-angular/fng-ui-date component.

The relevant line in the schema is at https://github.com/forms-angular/website/blob/master/app/models/b_enhanced_schema.js#L55.  See also  https://github.com/forms-angular/website/blob/master/app/index.html#L75 and https://github.com/forms-angular/website/blob/master/bower.json#L10).

Hope that helps.

**Comment by syedf** [comment]
Thanks for the reply, i did add all the files as you said, still doesnt work

i also tried adding directive as 'fng-ui-date'

 `date: { type: Date, form:{ label: "Publish date", helpInline: "defaults to today if left black", directive: "fng-ui-date"}},
`
it still doesn't work. anything that i may be missing?

**Comment by mchapman** [comment]
You don't need the directive.  Look at
https://github.com/forms-angular/website/blob/master/app/models/b_enhanced_schema.js#L55

**Comment by syedf** [comment]
i tried with and without the directive, i tried the directive one just to be sure

**Comment by mchapman** [comment]
If you use the yeoman generator
<https://github.com/forms-angular/generator-angular-fullstack> you can
include a date field - maybe you can look at the generated app and then
figure out where yours is different?
